### ISSUE TITLE
Forge2D docs link in README dead (404)

### ISSUE THREAD

**Issue by osharaki** [flame-engine/flame_box2d#15]
https://flame-engine.org/docs/forge2d.md points to a non-existent page. Where can I find the documentation for Forge2D?

**Comment by spydon** [comment]
It is slightly outdated, but here are the docs:
https://flame-engine.org/docs/box2d.md
(Replace all the box2d with forge2d)
We are updating all of them at the moment so soon they should get an update.

**Comment by spydon** [comment]
Should work now on the new site:
https://flame-engine.org/docs/#/docs/forge2d
