### ISSUE TITLE
Box2d wants meters but flame wants pixels

### ISSUE THREAD

**Issue by dynamicbutter** [flame-engine/flame_box2d#36]
When this mapping is not done properly Box2d behaves in unexpected ways, but dealing with both coordinate systems in multiple places is confusing.  I suggest a single place in flame_forge2d where the caller can define the value of `pixels-per-meter`.  Perhaps as an optional parameter to the Forge2dGame constructor.  Flame users can continue to deal with existing flame apis in pixels, and flame_forge2d can do all the conversions for us.

**Comment by spydon** [comment]
With the projection class coming from the new version of flame you have methods for this. For positions you can use `worldToScreen` and `screenToWorld` right now.

**Comment by dynamicbutter** [comment]
@spydon thanks, I'll look at that
