### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by definev** [flame-engine/flame_box2d#37]
![image](https://user-images.githubusercontent.com/62325868/119556637-78eff500-bdc9-11eb-84ec-c57a1942c623.png)
I trying to play-around with this package but got so many issues.

**Comment by spydon** [comment]
You have to use one of the earlier versions of the flame release candidates.
Try for example: flame_forge2d 0.6.0-rc2 with flame 1.0.0-rc5.

**Comment by definev** [comment]
I can't figure out, i'm downloading previous example version 0.6.0-rc1, work fine. However, the API is so unstable, i upgrade dependency have so many error 

> {
	"resource": "/D:/Github/flame_forge2d-0.6.0-rc1/flame_forge2d-0.6.0-rc1/example/lib/draggable_sample.dart",
	"owner": "dart",
	"code": {
		"value": "non_abstract_class_inherits_abstract_member",
		"target": {
			"$mid": 1,
			"external": "https://dart.dev/diagnostics/non_abstract_class_inherits_abstract_member",
			"path": "/diagnostics/non_abstract_class_inherits_abstract_member",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "Missing concrete implementations of 'BaseComponent.addChild', 'BaseComponent.addEffect', 'BaseComponent.clearChildren', 'BaseComponent.clearEffects', and 25 more.\nTry implementing the missing methods, or make the class abstract.",
	"source": "dart",
	"startLineNumber": 26,
	"startColumn": 7,
	"endLineNumber": 26,
	"endColumn": 20,
	"tags": []
}<

Seam to be BaseComponent is different in two package. I think this should be adding in core package. For instance, flame_core contains core interface for forge2d, flame, flame_forge2d etc ...

**Comment by spydon** [comment]
You didn't downgrade `flame`, you only downgraded `flame_forge2d`.

**Comment by definev** [comment]
Ok, thank you, I override the dependency and that works!
