### ISSUE TITLE
Not able to run Example

### ISSUE THREAD

**Issue by vijayb95** [flame-engine/flame_box2d#39]
Hello,

Tried running it directly from the parent package and got some errors, so specifically went to example folder and altered pubspec.yaml per the previously closed issue and got an error again. your time is much appreciated, thanks in advance!

![image](https://user-images.githubusercontent.com/63966603/120012867-b0df7e00-bffd-11eb-9a7e-c70fb50d813d.png)

**Comment by spydon** [comment]
Hey there,
you have to run the example for the version of `flame_forge2d` that you have in your pubspec file, the one on `main` is too new.
So you have to check on the tag which is corresponding to the version that you are running, which in your case is `v0.6.0-rc2`:
https://github.com/flame-engine/flame_forge2d/tree/v0.6.0-rc2

**Comment by vijayb95** [comment]
Thanks for quickly getting into it, I tried running v0.6.0-rc2 and all the previous errors are gone. But I got one new one, saying some context is missing. Looks like it is happening due Dashbook dependency. Is this something you can help with?

![image](https://user-images.githubusercontent.com/63966603/120016560-644a7180-c002-11eb-9e43-5828a8a61cce.png)

![image](https://user-images.githubusercontent.com/63966603/120016746-98be2d80-c002-11eb-8d3e-653faf6f48e2.png)
