### ISSUE TITLE
ChainShape in circle_stress_sample.dart

### ISSUE THREAD

**Issue by hmlyn523** [flame-engine/flame_box2d#40]
I ran circle_stress_sample.dart from the spydon.update-versions branch.
I deleted the left side of the two CornerRamps, and the right side shows up, but the hit decision is on the left side.

```
Future<void> onLoad() async {
    final boundaries = createBoundaries(viewport); 
    boundaries.forEach(add);
    add(CircleShuffler()); 
    add(CornerRamp(isMirrored: true));
    // add(CornerRamp(isMirrored: false)); 
}
```

**Comment by spydon** [comment]
Please don't report issues on unmerged branches in the future, but I will have a look.

**Comment by hmlyn523** [comment]
Sorry about that. Please take care of me.
